### ISSUE TITLE
Řazení oborů WoS JCR v dropdown menu

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#1]
# Popis: 
Do dropdown menu v sekcích **Časopisecké indikátory** a **Citační indikátory** přidat obory Web of Science.

- Seznam vědeckých oborů dle WoS JCR lze [získat zde (soubor Převodník oborů FORD/Wos.xlsx)](https://vyzkum.gov.cz/FrontClanek.aspx?idsekce=979300).
- Obory by v obou menu měly být **řazeny abecedně** a při rozkliknutí roletky by mělo být v její horní části umístěno vyhledávací pole, umožňující rychlou filtraci v rámci oborů - [příklad](https://www.w3schools.com/howto/howto_js_filter_dropdown.asp). 
- Dropdown menu by mělo mít v obou kategoriích identické chování.

**Comment by skocik-cosmotroncz** [comment]
Zavedl jsem novou komponentu „Select-search“. 
V konfiguraci „Časopiseckých indikátorů“ jsem takto nastavil  „Obor dle WoS JCR“.
K náhledu je tedy k dispozici na url:
https://sp-test.library.sk/cav-vyvoj7/zvolit-ustav/slu-s/#statistiky/periodika

**Comment by eli-blazek** [comment]
Funkcionalita otestovaná - vše funguje perfektně. 
Asi je to jasné, ale drobná úprava, kterou bych ještě přidala je scrollbar přímo do komponenty, který bude fungovat nezávisle na scrollbaru zbytku stránky.

**Comment by skocik-cosmotroncz** [comment]
Scrollbar v komponentě jsem zavedl (osa Y).

**Comment by eli-blazek** [comment]
Moc děkuju za rychlou reakci. Ještě pošlu k otestování kolegům.

**Comment by eli-blazek** [comment]
Otestováno, za nás vše v pořádku. Uzavírám issue. Děkuji.
