### ISSUE TITLE
UI - úprava logiky - fungování šipek u dropdown menu

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#11]
# Popis
- V celé aplikaci u dropdown menu je indikované zabalení/rozbalení prvku pomocí šipky nalevo od názvu prvku.
    - Např. u Publikace ASEP -> Rok vydání, Druh dokumentů nebo Přínos autorů -> Oddělení
- Šipka nahoru indikuje zabalenou roletku, šipka dolů rozbalenou. Toto neintuitivní UI design. 
#### Menu sbalené 
![CleanShot 2024-07-17 at 16 31 10@2x](https://github.com/user-attachments/assets/fcab6b0e-d1e4-479c-a573-12d5180ed5c5)

#### Menu rozbalené
![CleanShot 2024-07-17 at 16 31 36@2x](https://github.com/user-attachments/assets/f64dc46a-6d3f-4378-9bb5-185129a8146c)

# Řešení 
- Obrátit logiku tak, aby u sbalené rolety šipka ukazovala dolů (indikující možnost rozbalit) a při rozbalení ukazovala směrem nahoru (tedy indikovala možnost sbalit)

**Comment by skocik-cosmotroncz** [comment]
V komponentě Multi-select jsem změnil logiku šipek.

**Comment by eli-blazek** [comment]
Logika šipek funguje, jak má. Díky moc, uzavírám.
