### ISSUE TITLE
UI úpravy - sekce Zvolit ústav

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#12]
Související issue: #6 

Pro zlepšení čitelnosti a přehlednosti navrhuji následující změny: 
- širší dropdown menu - název žádného ústavu by neměl být zalomen přes několik řádek (v současné době např. *Ústav molekulární biologie rostlin* nebo *Společná laboratoř chemie pevných látek*)
- Zrušit kapitálky, názvy ústavů psané normálně

**Comment by skocik-cosmotroncz** [comment]
Dobrý den,
omlouvám se za zpoždění. 
Nasadil jsem úpravu na rozšíření dropdown menu + zrušeny kapitálky.

**Comment by eli-blazek** [comment]
Super, díky moc. 
Předáno kolegům k testování a evaluaci.

**Comment by eli-blazek** [comment]
Ještě jsem našla jeden detail a chtěla bych o něj rozšířit požadavek - zrušit kapitálky a název psát normálně i v rámci stránky specifického ústavu. 

-Jako příklad uvádím BFU
![CleanShot 2024-09-20 at 12 37 28](https://github.com/user-attachments/assets/2617b096-581c-4d97-a89e-deb4cfbb68bc)

**Comment by skocik-cosmotroncz** [comment]
Kapitálky v nadpise uvnitř zrušeny.

**Comment by eli-blazek** [comment]
Perfektní. Díky moc. 

Uzavírám.
