### ISSUE TITLE
Export - pdf + tisk upraven

### ISSUE THREAD

**Issue by skocik-cosmotroncz** [LIBCAS/Analytika-ASEP-2024#13]
Exportovací modul pdf – nově zavedena backendová komponenta „wkhtmltopdf“ pro export dat ve formátu pdf. 
Stávající systém na JS „html2pdf“ vzhledem k objemu a charakteru dat nevyhovoval, bylo obtížné jej odladit, odsunuto na backend řešení.

**Comment by eli-blazek** [comment]
Nové řešení funguje dobře. Změna dává smysl. Děkuji. Více viz #18. 

Tuto issue uzavírám.
