### ISSUE TITLE
Upravit logiku pro toggle "Export"

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#17]
## Současný stav - popis
![CleanShot 2024-11-12 at 11 13 18@2x](https://github.com/user-attachments/assets/8bc9de66-7035-490f-ac36-a8a253749dfc)
To, jak Export nyní funguje, a to jak ve staré, tak v nové verzi Analytik je to, že hodnoty "RIV" a "not RIV" jsou checkboxy. Pokud není zaškrtnutý žádný (výchozí stav), vyexportuje se všechno. Pokud jsou zaškrtnuté oba, taky se vyexportuje všechno. Pokud chce člověk exportovat pouze výsledky v RIVu, nebo naopak pouze výsledky mimo RIV, musí zaškrtnout pouze jeden z checkboxů. 
Jedná se o neintuitivní a nešťastné řešení. 

## Návrh na změnu
Proto navrhuji změnit na skupinu 3 radio buttons - "Vše", "RIV", "not RIV". "Vše" bude zaškrtnuté jako výchozí stav. V případě, že někdo chce vyexportovat pouze RIV, zaškrtne tlačítko "RIV". To samé v případě Not RIV. Předpokládané je výchozí chování Radio buttons. 

Mockup: 
![CleanShot 2024-11-12 at 11 23 19@2x](https://github.com/user-attachments/assets/f4846f57-a8fb-4751-84b5-de2f36afb3cb)

**Comment by skocik-cosmotroncz** [comment]
Ano, nachystám komponentu s radio buttons.

**Comment by skocik-cosmotroncz** [comment]
Nasadil jsem verzi s komponentou "radio buttons".
