### ISSUE TITLE
Přidání vyhledávacího pole

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#2]
# Popis 
- Přidat do horní lišty Analytik vyhledávací pole. 
    - Vyhledávání pomocí SYSNO a pomocí autora
    - Funkcionalita: viz stará Analytika

**Comment by skocik-cosmotroncz** [comment]
Vyhledávací pole je vloženo, zatím jen "odkaz" na stará Analytika.

**Comment by eli-blazek** [comment]
Díky. 

Zastavte mě, pokud je nějaký validní UX důvod to nedělat, ale měla bych ještě požadavek - šlo by vyhledávač rozšířit tak, aby jeho padding na pravé straně byl stejný, jako u ostatních prvků (tj. trochu to pole rozšířit - viz screenshot)
![CleanShot 2024-09-18 at 15 50 25@2x](https://github.com/user-attachments/assets/c7e10001-6730-4c94-afe6-f780af574259)

**Comment by eli-blazek** [comment]
Nyní opraveno. Děkuji. 

Uzavírám.
