### ISSUE TITLE
Fungování sekce Datové záznamy

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#22]
# Popis
Logika fungování sekce Datové záznamy momentálně nedává příliš smysl. Samozřejmě tato sekce nebyla přítomná v původních Analytikách, takže nebylo z čeho vycházet. 
Pokusím se popsat očekávanou funkcionalitu tak, aby dávala smysl. 

## Současný stav
![CleanShot 2024-11-12 at 15 33 13@2x](https://github.com/user-attachments/assets/f9818fca-168d-4fb4-af2c-f79d34659f01)
V sekci datových záznamů je jedna podsekce - je pojmenovaná "Datové záznam" a má dva checkboxy "Datasetem v jiném repozitáři" a "Datasetem v ASEP".
Jako výchozí není zaškrtnutý ani jeden.
To, co se zobrazuje, pokud není zaškrtnutý ani jeden checkbox jsou __bibliografické záznamy, které mají vytvořený odkaz na datový záznam.__

Pokud se zaškrtne "Datasetem v jiném repozitáři", nezobrazují se žádné záznamy. Nejsem si plně jistá, co je zamýšlenou funkcionalitou checkboxu (testováno na záznamech Fyzikálního ústavu). 

Pokud se zaškrtne "Datasetem v ASEP", zobrazí se datasety, které jsou přítomné v ASEPu. 

### Upravit texty 
- "Datové záznam" na "Datové záznamy"
- "Datasetem v jiném repozitáři"  na "Dataset v jiném repozitáři"
- "Datasetem v ASEP" na "Dataset v ASEP")

## Upravit sekci "Datové záznamy/Datové záznam"
- Bibliografické záznamy s odkazem na datový záznam (nyní výchozí chování když není zaškrtnutý žádný checkbox) by vůbec neměly v téhle sekci být
- Proto by dávalo smysl předělat tuhle sekci na set 2 radio buttons - "Dataset v ASEP" by bylo první, "Dataset v jiném repozitáři" jako druhé. Dataset v ASEP by bylo zaškrtnuté jako výchozí. 
Mockup:
![CleanShot 2024-11-12 at 15 54 19@2x](https://github.com/user-attachments/assets/d23f896b-00c0-4292-a0a9-bca08d76d936)
- Celá sekce Datové záznamy ASEP má sloužit primárně pro zobrazování datových záznamů

**Comment by skocik-cosmotroncz** [comment]
Upravil jsem texty.
Upravil, nasadil jsem zde komponentu "radio buttons", upravil jsem konfiguraci číselníku - řazení.

**Comment by eli-blazek** [comment]
Děkuji moc za úpravy, testovala jsem, funguje tak, jak by mělo. 

Možná na Datových záznamech bude potřeba ještě někdy něco měnit, ale prozatím vše funguje dle očekávání. 

Děkuji a uzavírám.
