### ISSUE TITLE
UI - rozlišení jednotlivých záznamů

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#27]
# Popis
Aplikace má v současné době problém, že jednotlivé záznamy jsou těžko čitelné a je obtížné na první pohled rozlišit, kde jeden záznam začíná a druhý končí. 
Bylo by třeba je od sebe nějak vizuálně odlišit. 

# Možná řešení problému
Různé aplikace k tomu přistupují různě. 
ASEP například přidává rozdělovací čáry mezi jednotlivé záznamy. 
![CleanShot 2024-11-19 at 16 25 03](https://github.com/user-attachments/assets/30f852cc-6320-4d02-a5af-c6c76107033d)

Stará Analytika ASEP mají nastavené jinou background barvu každého lichého záznamu plus mají mnohem výraznější margins kolem každého záznamu.
![CleanShot 2024-11-19 at 16 26 59](https://github.com/user-attachments/assets/782c9361-032f-4587-a026-e952682346ad)

**Osobně navrhuji kombinaci obou řešení - přidat dělící čáry mezi jednotlivé záznamy + mírně změnit barvu pozadí každého sudého záznamu.**

**Comment by skocik-cosmotroncz** [comment]
Vizuální odlišení zavedeno (jakákoliv úprava samozřejmě možná).

**Comment by eli-blazek** [comment]
Díky za zavedení. Otestováno. Výrazně to přidalo na čitelnosti. Prozatím uzavírám.
