### ISSUE TITLE
Dropdown menu "Druhy dokumentů" - oprava labelu L6 Inovace

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#4]
Opravit zabugovaný prvek L6 Inovace v dropdown menu Druhy dokumentů

![CleanShot 2024-07-17 at 10 04 08@2x](https://github.com/user-attachments/assets/0d506e28-fdb8-4400-9fcc-bf7a37aca617)

**Comment by skocik-cosmotroncz** [comment]
Label - "Inovace" v dropdown menu "Druhy dokumentů" opraveno (úprava konfigurace).

**Comment by eli-blazek** [comment]
Ano, opraveno. Potvrzuji a uzavírám. 

Díky.
