### ISSUE TITLE
Dropdown menu "Infrastruktury" - oprava labelu Infrastruktura a Infrastruktura - hostitel

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#5]
- V sekci Finanční podpora -> Velké výzkumné infrastruktury jsou rozbité labely Infrastruktura a Infrastruktura - hostitel v dropdown menu Infrastruktury
![CleanShot 2024-07-17 at 10 19 42@2x](https://github.com/user-attachments/assets/cc72c25d-d0f7-441d-8971-3c1e4de55d59)

**Comment by skocik-cosmotroncz** [comment]
Labely Infrastruktura a Infrastruktura - hostitel opraveny (úprava konfigurace).

**Comment by eli-blazek** [comment]
Potvrzuji, labely opravené. 

Uzavírám. 

Díky.
