### ISSUE TITLE
Dropdown menu "Vybrat ústav" - vyřadit zrušené a sloučené ústavy z abecedního řazení

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#6]
# Popis 
V dropdown menu "Vybrat ústav" v navigačním headeru jsou nyní v abecedním pořadí řazeny všechny ústavy. Včetně těch, které patří do seznamu "Zrušených a sloučených ústavů. 
 # Řešení
Odebrat zrušené a sloučené ústavy z abecedního řazení, vložit za oddělovač na konec dropdown menu
#### Mockup logiky
![CleanShot 2024-07-17 at 10 53 22@2x](https://github.com/user-attachments/assets/15a7c446-95b4-46a1-a4ab-db5b0b49add2)

#### Jmenovitě se jedná o tyto ústavy:
- Archiv AV ČR (od r. 2006 pod Masarykův ústav - Archiv AV ČR, v. v. i.)
- Entomologický ústav AV ČR, v. v. i. (BC od r. 2005)
- Hydrobiologický ústav, AV ČR, v. v. i. (BC od r. 2005)
- Masarykův ústav AV ČR (od r. 2006 pod Masarykův ústav a Archiv AV ČR, v. v. i.)
- Parazitologický ústav AV ČR, v. v. i. (BC od r. 2005)
- Společná laboratoř chemie pevných látek AV ČR (UP a AV ČR, od r. 2003 pod UMCH-V)
- Ústav molekulární biologie rostlin AV ČR, v. v. i. (BC od r. 2005)
- Ústav pro elektrotechniku AV ČR (od r. 2006 pod Ústavem pro termomechaniku AV ČR, v. v. i.)
- Ústav půdní biologie AV ČR, v. v. i. (BC od r. 2005)

**Comment by skocik-cosmotroncz** [comment]
V nabídce zvolit ústav jsou nyní zrušené ústavy umístěny na konec seznamu, za oddělením.

**Comment by eli-blazek** [comment]
Super, díky moc. 
Předáno kolegům k testování a evaluaci.

**Comment by eli-blazek** [comment]
Zkonzultováno. 

Díky. Uzavírám.
