### ISSUE TITLE
English version - odebrání zkratky v.v.i. z anglických verzí názvů ústavů AV ČR

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#7]
# Popis
Zkratka "v.v.i." znamená Veřejná výzkumná instituce. Tato zkratka se však uvadí **pouze** u českých verzí názvů AV ČR a jejich jednotlivých ústavů. Názvy ústavů v anglické verzi se uvádí bez této zkratky. 

Tj. 
Knihovna AV ČR, v. v. i. - Library of the CAS
Astronomický ústav AV ČR, v. v. i. - Astronomical institute of the CAS

# Řešení 
Odebrat zkratku v.v.i. za všemi názvy, které ji obsahují v anglické lokalizaci Analytik ASEP

**Comment by skocik-cosmotroncz** [comment]
Zkratky v.v.i. jsem v anglické lokalizaci odebral (úprava konfigurace).

**Comment by eli-blazek** [comment]
Vypadá to dobře. 

Ještě předám ke kontrole kolegům, abych něco nepřehlédla. 

Předběžně díky.

**Comment by eli-blazek** [comment]
Zkonzultováno. 

Díky. Uzavírám.
