### ISSUE TITLE
Upravit výchozí nastavení filtrů - celá aplikace

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#8]
# Popis 
Výchozí nastavení filtrů by mělo kopírovat nastavení filtrů u starých Analytik ASEP

Jmenovitě tedy: 
#### Rok vydání 
Posledních 5 let (tj. v r. 2024 bude vybráno: 2024, 2023, 2022, 2021, 2020)

#### Druh dokumentu 
**Vybrané hodnoty:** Článek v odborném periodiku, Článek v impaktovaném peridiku, Monografie (český jazyk), Monografie (cizí jazyk), Kapitola v monografii (český jazyk), Kapitola v monografii (cizí jazyk)

**Comment by skocik-cosmotroncz** [comment]
Nastavení "roky vydání" jsem upravil v konfiguracích. ($g)
S nastavením pro "Druh dokumentu" je to trošku složitější.
Data pro "Druh dokumentu" v tuto chvíli načítáme jednoduše z číselníku (ANALYTIKA_KONFIG_CIS_SZ), včetně vybraných hodnot. 
V původním systému nejsou data v jednotlivých "sekcích" (Ústav, Statistika ústavu) stejná.
Tento stav zatím datově podchycený není. Za mě tedy, zatím nechávám v aktuálním stavu k dopracování.

**Comment by eli-blazek** [comment]
Děkuji za řešení, vypadá dobře. 
Šlo by to prosím takhle propsat i do zbytku aplikace? Vypisuji, kde jsem si všimla, že není 5 let.
- Publikace ASEP (stále 2 roky)
- Datové záznamy v ASEP (z nějakého důvodu 4 roky)
- Přehled oddělení (stále 2 roky)
- Přehled periodik (6 let)
- Velké výzkumné infrastruktury (4 roky)
- Inst. podpora - záznamy (1 rok)
- Inst. podpora - počty záznamů (1 rok)

**Comment by skocik-cosmotroncz** [comment]
Omlouvám se za nedorozumění, nastavil jsem původně dle hodnot staré aplikace.
Upravil jsem konfigurace, roky 2024-2020, respektive automaticky posledních 5 let.

**Comment by eli-blazek** [comment]
Děkuji, otestovala jsem, vypadá to už mnohem lépe. 
Jen drobná poznámka - v **sekcích Časopisecké indikátory, Citační indikátory a Přehled indikátorů pro ústav** jsou pořád nastaveny poslední 3 roky.

**Comment by skocik-cosmotroncz** [comment]
Dobrý den, 
ano, děkuji, u těch tří jsem upravil konfigurace - pevné nastavení vybraných let na 2022-2018.

**Comment by eli-blazek** [comment]
Omlouvám se za prodlevu, funguje jak má. Děkuji za úpravu. 

Uzavírám.
