### ISSUE TITLE
Načítání výsledků při prvotním načtení stránky

### ISSUE THREAD

**Issue by eli-blazek** [LIBCAS/Analytika-ASEP-2024#9]
# Popis
- V současné době se výsledky na stránce načítají až při kliknutí na button "Zobrazit výsledky"
- Po načtení se výsledky zobrazují v bibliografickém formátu. 

# Řešení 
- Změnit tak, aby se výsledky načítali už při prvním načtení stránky. Jako filtry by měly být nastavené výchozí hodnoty (nastavení výchozích hodnot viz #8 ). 
- Zobrazené výsledky by měly být v **Výchozím formátu**, ne v bibliografickém.

**Comment by skocik-cosmotroncz** [comment]
Zavedl jsem automatické zpracování dat po načtení stránky.
Upravil jsem konfigurace, nastaven jako výchozí formát: "zkrácený formát".

**Comment by eli-blazek** [comment]
Na první pohled vypadá velmi dobře. 
Ještě chci trochu víc detailně otestovat, zaznamenala jsem párkrát při načítání zvláštní chování stránky a několikanásobný loading. 
Nejspíš ale bylo způsobené z mojí strany, protože side panel + Inspector window vytvořily fakt divné rozlišení (1145 x 1050 px), takže může jít o nějaký edge case. 
Při normálních rozlišeních (16:9, 16:10) se chová, jak má.

**Comment by eli-blazek** [comment]
Zkonzultováno. 

Díky. Uzavírám.
